### ISSUE TITLE
Allow running Poetry with a non-default Python version

### ISSUE THREAD

**Issue by brechtm** [Gr1N/setup-poetry#8]
I'm trying to run my tests with Python 3.10. However, Poetry doesn't support 3.10 yet and crashes.

Locally, I can run Poetry using another Python version than the one used for the virtualenv set up by Poetry. Is the same possible somehow with setupoetry?

**Comment by tueda** [comment]
This feature will be also useful for testing old Python versions.

For now, the following hack seems to work:
```yaml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
      - id: python-path
        run: echo "::set-output name=path::$(command -v python)"
      - uses: Gr1N/setup-poetry@v4
      - id: poetry-path
        run: echo "::set-output name=path::$(command -v poetry)"
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10-dev
      - run: sed -i '1i#!${{ steps.python-path.outputs.path }}' '${{ steps.poetry-path.outputs.path }}'
      - run: poetry env use 3.10

      - run: poetry run python --version
      - run: poetry install
```
